export const ENDPOINTS = {
  AUTH: {
    REGISTER: 'register',
    VERIFY_OTP: 'verify-otp',
    SET_PASSWORD: 'set-password',
    RESEND_OTP: 'resend-otp',
    LOGIN: 'login',
    CREATE_PROFILE: 'create-profile',
    GOOGLE: 'google',
    REDIRECT_GOOGLE: 'google/redirect',
    GET_PROFILE: 'get-profile',
    EDIT_PROFILE: 'update-profile',
    FORGOT_PASSWORD: 'forgot-password',
    REQUEST_DELETE_OTP:'request-delete-otp',
    VERIFY_DELETE_OTP:'verify-delete-otp',

  },
  BANK: {
    BANK_NAMES: 'names',
    ACCOUNT_TYPES: 'account-types',
    CURRENCIES: 'currencies',
    ADD_ACCOUNT: 'add-account',
    ADD_PLAID_ACCOUNT: 'add-plaid-account',
    SYNC_PLAID_ACCOUNT: 'sync/:bankId',
    EDIT_ACCOUNT: 'edit-account/:id',
    GET_BANK_HISTORY: 'bank-history/:id',
    DELETE_ACCOUNT: 'delete-account/:id',
    USER_BANK_ACOOUNTS: 'user-bank-accounts',
    NET_BANK_BALANCE: 'net-bank-balance',
    NET_WORTH: 'net-worth',
    NET_WORTH_HISTORY: 'net-worth-history',
  },
  INCOME: {
    ADD_INCOME: 'add',
    DELETE_INCOME: 'delete/:incomeId',
    EDIT_INCOME: 'edit/:incomeId',
    GET_NET_INCOME: 'net-income',
  },
  BUDGET: {
    ADD_BUDGET: 'add',
    DELETE_BUDGET: 'delete/:budgetId',
    EDIT_BUDGET: 'edit/:budgetId',
    GET_NET_BUDGET: 'net-budget',
  },
  EXPENSE: {
    ADD_EXPENSE: 'add',
    DELETE_EXPENSE: 'delete/:expenseId',
    EDIT_EXPENSE: 'edit/:expenseId',
    GET_NET_EXPENSE: 'net-expense',
    GET_AVERAGE_EXPENSE: 'average-expense',
    GET_TOP_MERCHANTS: 'top-merchants',
    GET_TOP_CATEGORIES: 'top-categories',
  },
  PLAID: {
    CREATE_LINK_TOKEN: 'create-link-token',
    CATEGORIES: 'categories',
  },
  FINANCIALITEMS: {
    ADD_FINANCIAL_ITEM: 'add',
    EDIT_FINANCIAL_ITEM: 'edit/:id',
    DELETE_FINANCIAL_ITEM: 'delete/:id',
    GET_USER_FINANCIAL_ITEMS: 'user-items',
    NET_ASSETS: 'net-assets',
    NET_LIABILITIES: 'net-liabilities',
  },
  ADMIN: {
    REGISTER: 'register',
    LOGIN: 'login',
    GET_PROFILE: 'get-profile',
    All_USERS: 'all-users',
    USER_DETAILS: 'user/:userId',
    ALL_ADMINS: 'all-admins',
    USERS_COUNT: 'users-count',
    UPDATE_PROFILE: 'update-profile',
    BLOCK_USER: 'block-user/:userId',
    UNBLOCK_USER: 'unblock-user/:userId',
    DElETE_USER: 'delete-user/:userId',
  },
  TRANSACTION: {
    EDIT_TRANSACTION: '/:transactionId',
    DELETE_TRANSACTION: '/:transactionId',
  },
};
export const AppConst = {
  SWAGGER_URL: 'swagger/api',
};
export enum SyncType {
  CRON = 'CRON',
  USER = 'USER',
}
