export const incomeCategories = new Set([
  'Payroll',
  'Deposits',
  'Refunds',
  'Gifts and Donations',
  'Interest',
  'Transfer',
  'Deposit',
  'Payroll',
  'INCOME',
  'TRANSFER_IN',
  'INVESTMENT',
  'Salary',
  'Dividend',
]);
export const expenseCategories = new Set([
  'Food and Drink',
  'Travel',
  'Shopping',
  'Entertainment',
  'Health and Wellness',
  'Transportation',
  'Home Improvement',
  'Bills and Utilities',
  'Insurance',
  'Personal Care',
  'Subscriptions',
  'Education',
  'Government and Taxes',
  'Fees and Charges',
  'Airlines and Aviation Services',
  'Taxi',
  'TRANSPORTATION',
  'Restaurants',
  'ENTERTAINMENT',
  'Payment',
  'GENERAL_MERCHANDISE',
  'Fast Food',
  'FOOD_AND_DRINK',
  'Shops',
  'Sporting Goods',
  'Credit Card',
  'LOAN_PAYMENTS',
  'GENERAL_SERVICES',
  'Recreation',
  'Gyms and Fitness Centers',
  'PERSONAL_CARE',
  'Coffee Shop',
  'Debit',
  'EXPENSE',
  'TRANSFER_OUT',
  'LOAN',
  'Airlines',
  'Coffee Shop',
]);
export const categories = [
  { category: 'Salary', type: 'income' },
  { category: 'Groceries', type: 'expense' },
  { category: 'Utilities', type: 'expense' },
  { category: 'Business Income', type: 'income' },
  { category: 'Taxes & Government Payments', type: 'expense' },
  { category: 'Business Expenses', type: 'expense' },
  { category: 'Rent & Mortgage', type: 'expense' },
  { category: 'Travel', type: 'expense' },
  { category: 'Home Maintenance & Repairs', type: 'expense' },
  { category: 'Online Trading', type: 'both' },
  { category: 'Phone & Internet', type: 'expense' },
  { category: 'Freelance', type: 'income' },
  { category: 'Dividend', type: 'income' },
  { category: 'Capital Gains', type: 'income' },
  { category: 'Grants / Scholarships', type: 'income' },
  { category: 'Interest Income', type: 'income' },
  { category: 'Rental Income', type: 'income' },
  { category: 'Loan Payments', type: 'expense' },
  { category: 'Dining & Takeout', type: 'expense' },
  { category: 'Entertainment', type: 'expense' },
  { category: 'Income', type: 'income' },
  { category: 'Transportation', type: 'expense' },
  { category: 'Medical & Pharmacy', type: 'expense' },
  { category: 'Childcare & Tuition', type: 'expense' },
  { category: 'Subscriptions & Streaming Services', type: 'expense' },
  { category: 'Health & Fitness', type: 'expense' },
  { category: 'Personal Care', type: 'expense' },
  { category: 'Shopping', type: 'expense' },
  { category: 'Transfers & Internal Accounts', type: 'both' },
  { category: 'Deposit', type: 'income' },
  { category: 'Payroll', type: 'income' },
  { category: 'Insurance', type: 'expense' },
  { category: 'Gifts & Donations', type: 'expense' },
  { category: 'Investments & Brokerage', type: 'both' },
  { category: 'Bank Fees & Interest', type: 'expense' },
];
