export interface Bank {
  name: string;
}
const banks: Bank[] = [
  { name: "B2B Bank" },
  { name: "Bank of Montreal (BMO)" },
  { name: "Bank of Nova Scotia (Scotiabank)" },
  { name: "Bridgewater Bank" },
  { name: "Caisse populaire acadienne ltée" },
  { name: "Canadian Imperial Bank of Commerce (CIBC)" },
  { name: "Canadian Tire Bank" },
  { name: "Canadian Western Bank" },
  { name: "Coast Capital Savings Federal Credit Union" },
  { name: "Concentra Bank" },
  { name: "CS Alterna Bank" },
  { name: "Digital Commerce Bank" },
  { name: "Equitable Bank" },
  { name: "Exchange Bank of Canada" },
  { name: "Fairstone Bank of Canada" },
  { name: "First Nations Bank of Canada" },
  { name: "General Bank of Canada" },
  { name: "Haventree Bank" },
  { name: "Home Bank" },
  { name: "HomeEquity Bank" },
  { name: "Innovation Federal Credit Union" },
  { name: "Laurentian Bank of Canada" },
  { name: "Manulife Bank of Canada" },
  { name: "Motus Bank" },
  { name: "National Bank of Canada" },
  { name: "Peoples Bank of Canada" },
  { name: "President's Choice Bank" },
  { name: "RFA Bank of Canada" },
  { name: "Rogers Bank" },
  { name: "Royal Bank of Canada (RBC)" },
  { name: "Tangerine Bank" },
  { name: "Toronto-Dominion Bank (TD)" },
  { name: "Vancity Community Investment Bank" },
  { name: "VersaBank" },
  { name: "Wealth One Bank of Canada" },
  { name: "AMEX Bank of Canada" },
  { name: "Bank of China (Canada)" },
  { name: "Cidel Bank Canada" },
  { name: "Citco Bank Canada" },
  { name: "Citibank Canada" },
  { name: "CTBC Bank Corp. (Canada)" },
  { name: "Habib Canadian Bank" },
  { name: "HSBC Bank Canada" },
  { name: "ICICI Bank Canada" },
  { name: "Industrial and Commercial Bank of China (Canada)" },
  { name: "J.P. Morgan Bank Canada" },
  { name: "KEB Hana Bank Canada" },
  { name: "SBI Canada Bank" },
  { name: "Shinhan Bank Canada" },
  { name: "UBS Bank (Canada)" },
  { name: "Bank of America, National Association" },
  { name: "Bank of China Limited" },
  { name: "Bank of New York Mellon" },
  { name: "Barclays Bank PLC" },
  { name: "Bank of Tokyo-Mitsubishi UFJ, Ltd." },
  { name: "BNP Paribas" },
  { name: "Capital One Bank (USA), N.A." },
  { name: "China Construction Bank" },
  { name: "Citibank, N.A." },
  { name: "Comerica Bank" },
  { name: "Deutsche Bank AG" },
  { name: "Fifth Third Bank National Association" },
  { name: "First Commercial Bank" },
  { name: "JPMorgan Chase Bank, National Association" },
  { name: "M&T Bank" },
  { name: "Maple Bank GmbH" },
  { name: "Mega International Commercial Bank Co., Ltd." },
  { name: "Mizuho Bank, Ltd. (Canada Branch)" },
  { name: "MUFG Bank, Ltd." },
  { name: "Northern Trust Company, Canada Branch" },
  { name: "PNC Bank, National Association" },
  { name: "Rabobank Nederland" },
  { name: "Société Générale (Canada Branch)" },
  { name: "State Street" },
  { name: "Sumitomo Mitsui Banking Corporation, Canada Branch" },
  { name: "U.S. Bank National Association" },
  { name: "United Overseas Bank Limited" },
  { name: "Wells Fargo Bank, National Association, Canadian Branch" }
];

export { banks }; 